name: CI

on:
  pull_request:
  push:

jobs:
  repro:
    name: Repro issue
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build baseline
        run: bun build --compile --minify --sourcemap index.ts --target=bun-windows-x64-baseline
    
